smtp:
  port: 25
  sessionTimeout: 60000

imap:
   port: 25000
   sessionTimeout: 60000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail
    username: root
    password: azerty
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect